name: Dev CI

on:
  push:
    branches:
      # on all branches except main where full build will be run
      - '*'
      - '!main'

jobs:
  linux_build:
    name: Build linux ${{ matrix.python.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '1.9'
          - '1' # Leave this line unchanged. '1' will automatically expand to the latest stable 1.x release of Julia.
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      - name: Build
        run: |
          julia build_local.jl --verbose   
